baseURL = 'https://example.com/'
locale = 'en-us'
title = "Duckye's Blog"
theme = "ghostwriter"

[Params]
mainSections = ["post"]
intro = true
headline = "Duckye's Blog"
description = "From huge achievements to random thoughts"
github = "https://github.com/RattlePenguin"
twitter = "https://twitter.com/RattlePenguin"
email = "pkgay9@gmail.com"
opengraph = true
shareTwitter = true
dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
post = "/:contentbasename/"
